### ISSUE TITLE
Investigate why black pre-commit hook fails

### ISSUE THREAD

**Issue by dpalmasan** [dpalmasan/python-user-posts-microservice#19]
Not sure why I get this error when running black on pre-commit. As a workaround currenly `poetry run black .` is being used.

```
black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "/home/dpalma/.cache/pre-commit/reporuiqo72y/py_env-python3.8/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/dpalma/.cache/pre-commit/reporuiqo72y/py_env-python3.8/lib/python3.8/site-packages/black/__init__.py", line 6606, in patched_main
    patch_click()
  File "/home/dpalma/.cache/pre-commit/reporuiqo72y/py_env-python3.8/lib/python3.8/site-packages/black/__init__.py", line 6595, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/home/dpalma/.cache/pre-commit/reporuiqo72y/py_env-python3.8/lib/python3.8/site-packages/click/__init__.py)
```

**Comment by dpalmasan** [comment]
It seems it was related to [ImportError: cannot import name '_unicodefun' from 'click'](https://github.com/pallets/click/issues/2225). Updating to `8.1.2` fixed the error.
